# Generated by Django 2.0.2 on 2020-10-21 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0004_auto_20170519_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='unique_computer_processor',
            field=models.CharField(max_length=255, null=True, verbose_name='Computer Processor'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
