# Generated by Django 2.0.2 on 2020-10-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djadmin', '0005_auto_20201021_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='ipaddress',
            field=models.CharField(max_length=100, null=True, verbose_name='IP Address'),
        ),
    ]
